apiVersion: v1
kind: Service
metadata:
  name: hermes-server
  labels:
    app.kubernetes.io/name: hermes
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: hermes
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
