apiVersion: v1
kind: Service
metadata:
  name: iris-server
  labels:
    app.kubernetes.io/name: iris
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/path: /metrics
    prometheus.io/scheme: https
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: iris
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
